const allLanguages = [
  "African languages",
  "Arabic",
  "Armenian",
  "Bengali",
  "Chinese",
  "Dutch",
  "English",
  "Filipino",
  "French",
  "German",
  "Greek",
  "Gujarati",
  "Hebrew",
  "Hindi",
  "Hungarian",
  "Italian",
  "Japanese",
  "Korean",
  "Laotian",
  "Marathi",
  "Miao,Hmong",
  "Mon-Khmer,Cambodian",
  "Navajo",
  "Other and unspecified languages",
  "Other Asian languages",
  "Other Indic languages",
  "Other Indo-European languages",
  "Other Native North American languages",
  "Other Slavic languages", 
  // "Patient Declined", 
  "Persian",
  "Polish",
  "Portuguese",
  "Romanian",
  "Russian",
  "Scandinavian languages", 
  "Serbo-Croatian",
  "Spanish",
  "Telugu",
  "Thai",
  "Urdu",
  "Vietnamese",
  "Yiddish",
]

export default allLanguages