const allSpecialties = [
  "Allergist(Immunologist)",
  "Cardiac Electrophysiologist",
  "Cardiologist(Heart Doctor)",
  "Cardiothoracic Surgeon",
  "Chiropractor",
  "Colorectal Surgeon",
  "Dentist",
  "Dermatologist",
  "Dietitian",
  "Dietitian / Nutritionist",
  "Ear, Nose & Throat Doctor(ENT)",
  "Emergency Medicine Physician",
  "Endocrinologist(incl Diabetes Specialists)",
  "Family Physician",
  "Gastroenterologist",
  "Hematologist(Blood Specialist)",
  "Infectious Disease Specialist",
  "Infertility Specialist",
  "Internist",
  "Midwife",
  "Naturopathic Doctor",
  "Nephrologist(Kidney Specialist)",
  "Neurologist(incl Headache Specialists)",
  "Neurosurgeon",
  "OB-GYN(Obstetrician-Gynecologist)",
  "Oncologist",
  "Ophthalmologist",
  "Optometrist",
  "Oral Surgeon",
  "Orthodontist",
  "Orthopedic Surgeon(Orthopedist)",
  "Pain Management Specialist",
  "Pediatric Dentist",
  "Pediatrician",
  "Physiatrist(Physical Medicine)",
  "Physical Therapist()",
  "Plastic Surgeon",
  "Podiatrist(Foot and Ankle Specialist)",
  "Primary Care Doctor(PCP)",
  "Prosthodontist",
  "Psychiatrist",
  "Psychologist",
  "Pulmonologist(Lung Doctor)",
  "Radiologist",
  "Rheumatologist",
  "Sleep Medicine Specialist",
  "Sports Medicine Specialist",
  "Surgeon",
  "Therapist / Counselor",
  "Travel Medicine Specialist",
  "Urgent Care Specialist",
  "Urological Surgeon",
  "Urologist",
  "Vascular Surgeon",
]

export default allSpecialties