const allTitles = [
  // {value: "ACCT", label:"Accountant (ACCT)"},
	{value: "LAC", label:"Acupuncturist (LAC)"},
	{value: "AUD", label:"Audiologist (AUD)"},
	// {value: "BILLINGMANAGER", label:"Billing Manager (BILLINGMANAGER)"},
	// {value: "BK", label:"Book Keeper (BK)"},
	{value: "CNM", label:"Certified Nurse Midwife (CNM)"},
	{value: "CRNA", label:"Certified Registered Nurse Anesthetist (CRNA)"},
	{value: "CRT", label:"Certified Respiratory Therapist (CRT)"},
	// {value: "CLERK", label:"Clerk (CLERK)"},
	{value: "CRN", label:"Credential Radiologic Nurse (CRN)"},
	{value: "DC", label:"Doctor of Chiropractic (DC)"},
	{value: "DMD", label:"Doctor of Dental Medicine (DMD)"},
	{value: "DDS", label:"Doctor of Dental Surgery (DDS)"},
	{value: "DMSc", label:"Doctor of Medical Science (DMSc)"},
	{value: "MD", label:"Doctor of Medicine (MD)"},
	{value: "OD", label:"Doctor of Optometry (OD)"},
	{value: "DO", label:"Doctor of Osteopathy (DO)"},
	{value: "DPM", label:"Doctor of Podiatric Medicine (DPM)"},
	{value: "PhD", label:"Doctors of Philosophy (PhD)"},
	// {value: "RECPT", label:"Front Desk/Receptionist (RECPT)"},
	{value: "HEADNU", label:"Head Nurse (HEADNU)"},
	// {value: "HOUSEKEEPING", label:"House Keeping (HOUSEKEEPING)"},
	{value: "LPN", label:"Licensed Practical Nurse (LPN)"},
	{value: "MS", label:"Master of Science (MS)"},
	{value: "MA", label:"Medical Assistant (MA)"},
	// {value: "MEDBILL", label:"Medical Biller (MEDBILL)"},
	// {value: "MEDIR", label:"Medical Director (MEDIR)"},
	// {value: "MEDSCRIBE", label:"Medical Transcriber (MEDSCRIBE)"},
	{value: "NP", label:"Nurse Practitioner (NP)"},
	{value: "OT", label:"Occupational Therapist (OT)"},
	// {value: "OFMGR", label:"Office Manager (OFMGR)"},
	{value: "RD", label:"Registered Dietitian (RD)"},
	{value: "PHAR", label:"Pharmacist (PHAR)"},
	{value: "PT", label:"Physical Therapist or Physiotherapist (PT)"},
	{value: "PTA", label:"Physical Therapy Assistant (PTA)"},
	{value: "PA", label:"Physician Assistant (licensed) (PA)"},
	{value: "RN", label:"Registered Nurse (RN)"},
	{value: "RRT", label:"Registered Respiratory Therapist (RRT)"},
	{value: "SW", label:"Social Worker (SW)"},
	{value: "ST", label:"Speech Therapist (ST)"},
]

export default allTitles